### ISSUE TITLE
MQTT source already implemented?

### ISSUE THREAD

**Issue by hubecker** [micw/homedatabroker#15]
As i can see from. the file ConfigFileParser.java there is already MQTT as SOURCE kind of implemented.
Can i use it already and can you give me an config example ?

Thanks

Hubert

**Comment by micw** [comment]
It is already implemented and I use it in "production" quite a long time and it works stable.

I have added an example: https://github.com/micw/homedatabroker/blob/master/Examples.md

**Comment by hubecker** [comment]
Thanks for the example. Works as expected.
